// flow-typed signature: b71fdfc271dd24fc2f6be1ed74576871
// flow-typed version: <<STUB>>/material-ui/AppBar_v1.0.0-beta.40/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'material-ui/AppBar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'material-ui/AppBar' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'material-ui/AppBar/AppBar' {
  declare module.exports: any;
}

// Filename aliases
declare module 'material-ui/AppBar/AppBar.js' {
  declare module.exports: $Exports<'material-ui/AppBar/AppBar'>;
}
declare module 'material-ui/AppBar/index' {
  declare module.exports: $Exports<'material-ui/AppBar'>;
}
declare module 'material-ui/AppBar/index.js' {
  declare module.exports: $Exports<'material-ui/AppBar'>;
}
