// flow-typed signature: 74aef22dadbf68aa42e9709c519047b5
// flow-typed version: <<STUB>>/material-ui/Button_v1.0.0-beta.40/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'material-ui/Button'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'material-ui/Button' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'material-ui/Button/Button' {
  declare module.exports: any;
}

// Filename aliases
declare module 'material-ui/Button/Button.js' {
  declare module.exports: $Exports<'material-ui/Button/Button'>;
}
declare module 'material-ui/Button/index' {
  declare module.exports: $Exports<'material-ui/Button'>;
}
declare module 'material-ui/Button/index.js' {
  declare module.exports: $Exports<'material-ui/Button'>;
}
