// flow-typed signature: 966221459745f11cacb19e884aa5cb24
// flow-typed version: <<STUB>>/material-ui/Checkbox_v1.0.0-beta.40/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'material-ui/Checkbox'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'material-ui/Checkbox' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'material-ui/Checkbox/Checkbox' {
  declare module.exports: any;
}

// Filename aliases
declare module 'material-ui/Checkbox/Checkbox.js' {
  declare module.exports: $Exports<'material-ui/Checkbox/Checkbox'>;
}
declare module 'material-ui/Checkbox/index' {
  declare module.exports: $Exports<'material-ui/Checkbox'>;
}
declare module 'material-ui/Checkbox/index.js' {
  declare module.exports: $Exports<'material-ui/Checkbox'>;
}
