// flow-typed signature: fae3364bebc3c203308cc831bd1f2c50
// flow-typed version: <<STUB>>/material-ui/CssBaseline_v1.0.0-beta.40/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'material-ui/CssBaseline'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'material-ui/CssBaseline' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'material-ui/CssBaseline/CssBaseline' {
  declare module.exports: any;
}

// Filename aliases
declare module 'material-ui/CssBaseline/CssBaseline.js' {
  declare module.exports: $Exports<'material-ui/CssBaseline/CssBaseline'>;
}
declare module 'material-ui/CssBaseline/index' {
  declare module.exports: $Exports<'material-ui/CssBaseline'>;
}
declare module 'material-ui/CssBaseline/index.js' {
  declare module.exports: $Exports<'material-ui/CssBaseline'>;
}
