// flow-typed signature: 46a4f465fc83c7e2341f5243df4cabc8
// flow-typed version: <<STUB>>/material-ui/Divider_v1.0.0-beta.40/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'material-ui/Divider'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'material-ui/Divider' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'material-ui/Divider/Divider' {
  declare module.exports: any;
}

// Filename aliases
declare module 'material-ui/Divider/Divider.js' {
  declare module.exports: $Exports<'material-ui/Divider/Divider'>;
}
declare module 'material-ui/Divider/index' {
  declare module.exports: $Exports<'material-ui/Divider'>;
}
declare module 'material-ui/Divider/index.js' {
  declare module.exports: $Exports<'material-ui/Divider'>;
}
