// flow-typed signature: 72bfc9fabc3b2d97cf90d4a1a74cce93
// flow-typed version: <<STUB>>/material-ui/Form_v1.0.0-beta.40/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'material-ui/Form'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'material-ui/Form' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'material-ui/Form/FormControl' {
  declare module.exports: any;
}

declare module 'material-ui/Form/FormControlLabel' {
  declare module.exports: any;
}

declare module 'material-ui/Form/FormGroup' {
  declare module.exports: any;
}

declare module 'material-ui/Form/FormHelperText' {
  declare module.exports: any;
}

declare module 'material-ui/Form/FormLabel' {
  declare module.exports: any;
}

// Filename aliases
declare module 'material-ui/Form/FormControl.js' {
  declare module.exports: $Exports<'material-ui/Form/FormControl'>;
}
declare module 'material-ui/Form/FormControlLabel.js' {
  declare module.exports: $Exports<'material-ui/Form/FormControlLabel'>;
}
declare module 'material-ui/Form/FormGroup.js' {
  declare module.exports: $Exports<'material-ui/Form/FormGroup'>;
}
declare module 'material-ui/Form/FormHelperText.js' {
  declare module.exports: $Exports<'material-ui/Form/FormHelperText'>;
}
declare module 'material-ui/Form/FormLabel.js' {
  declare module.exports: $Exports<'material-ui/Form/FormLabel'>;
}
declare module 'material-ui/Form/index' {
  declare module.exports: $Exports<'material-ui/Form'>;
}
declare module 'material-ui/Form/index.js' {
  declare module.exports: $Exports<'material-ui/Form'>;
}
