// flow-typed signature: 6cc8647add314bdf3dcc67045e187ae3
// flow-typed version: <<STUB>>/material-ui/IconButton_v1.0.0-beta.40/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'material-ui/IconButton'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'material-ui/IconButton' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'material-ui/IconButton/IconButton' {
  declare module.exports: any;
}

// Filename aliases
declare module 'material-ui/IconButton/IconButton.js' {
  declare module.exports: $Exports<'material-ui/IconButton/IconButton'>;
}
declare module 'material-ui/IconButton/index' {
  declare module.exports: $Exports<'material-ui/IconButton'>;
}
declare module 'material-ui/IconButton/index.js' {
  declare module.exports: $Exports<'material-ui/IconButton'>;
}
