// flow-typed signature: 6b9e00ff93aa12b06be12fdb1c682592
// flow-typed version: <<STUB>>/material-ui/Menu_v1.0.0-beta.40/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'material-ui/Menu'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'material-ui/Menu' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'material-ui/Menu/Menu' {
  declare module.exports: any;
}

declare module 'material-ui/Menu/MenuItem' {
  declare module.exports: any;
}

declare module 'material-ui/Menu/MenuList' {
  declare module.exports: any;
}

// Filename aliases
declare module 'material-ui/Menu/index' {
  declare module.exports: $Exports<'material-ui/Menu'>;
}
declare module 'material-ui/Menu/index.js' {
  declare module.exports: $Exports<'material-ui/Menu'>;
}
declare module 'material-ui/Menu/Menu.js' {
  declare module.exports: $Exports<'material-ui/Menu/Menu'>;
}
declare module 'material-ui/Menu/MenuItem.js' {
  declare module.exports: $Exports<'material-ui/Menu/MenuItem'>;
}
declare module 'material-ui/Menu/MenuList.js' {
  declare module.exports: $Exports<'material-ui/Menu/MenuList'>;
}
