// flow-typed signature: c4f43dd7818e1c79c373da3ae55dc40e
// flow-typed version: <<STUB>>/material-ui/Toolbar_v1.0.0-beta.40/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'material-ui/Toolbar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'material-ui/Toolbar' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'material-ui/Toolbar/Toolbar' {
  declare module.exports: any;
}

// Filename aliases
declare module 'material-ui/Toolbar/index' {
  declare module.exports: $Exports<'material-ui/Toolbar'>;
}
declare module 'material-ui/Toolbar/index.js' {
  declare module.exports: $Exports<'material-ui/Toolbar'>;
}
declare module 'material-ui/Toolbar/Toolbar.js' {
  declare module.exports: $Exports<'material-ui/Toolbar/Toolbar'>;
}
