// flow-typed signature: 3ad60762bbd1c50ab27c6f1622dbb444
// flow-typed version: <<STUB>>/material-ui/Typography_v1.0.0-beta.40/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'material-ui/Typography'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'material-ui/Typography' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'material-ui/Typography/Typography' {
  declare module.exports: any;
}

// Filename aliases
declare module 'material-ui/Typography/index' {
  declare module.exports: $Exports<'material-ui/Typography'>;
}
declare module 'material-ui/Typography/index.js' {
  declare module.exports: $Exports<'material-ui/Typography'>;
}
declare module 'material-ui/Typography/Typography.js' {
  declare module.exports: $Exports<'material-ui/Typography/Typography'>;
}
