// flow-typed signature: 5099610a1db1a0c020ebf8585d564490
// flow-typed version: <<STUB>>/redux-saga/effects_v0.2.6/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-saga/effects'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-saga/effects' {
  declare module.exports: any;
}
