// flow-typed signature: f8c65aed0537d51de87bc6befcca5c63
// flow-typed version: <<STUB>>/material-ui/Drawer_v1.0.0-beta.40/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'material-ui/Drawer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'material-ui/Drawer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'material-ui/Drawer/Drawer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'material-ui/Drawer/Drawer.js' {
  declare module.exports: $Exports<'material-ui/Drawer/Drawer'>;
}
declare module 'material-ui/Drawer/index' {
  declare module.exports: $Exports<'material-ui/Drawer'>;
}
declare module 'material-ui/Drawer/index.js' {
  declare module.exports: $Exports<'material-ui/Drawer'>;
}
