// flow-typed signature: 6ee0731f9bf85dcbff6152c3f1689b1f
// flow-typed version: <<STUB>>/material-ui/Icon_v1.0.0-beta.40/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'material-ui/Icon'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'material-ui/Icon' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'material-ui/Icon/Icon' {
  declare module.exports: any;
}

// Filename aliases
declare module 'material-ui/Icon/Icon.js' {
  declare module.exports: $Exports<'material-ui/Icon/Icon'>;
}
declare module 'material-ui/Icon/index' {
  declare module.exports: $Exports<'material-ui/Icon'>;
}
declare module 'material-ui/Icon/index.js' {
  declare module.exports: $Exports<'material-ui/Icon'>;
}
