// flow-typed signature: 15d9702d4296ef33bfef1ee5cba521fd
// flow-typed version: <<STUB>>/material-ui/List_v1.0.0-beta.40/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'material-ui/List'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'material-ui/List' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'material-ui/List/List' {
  declare module.exports: any;
}

declare module 'material-ui/List/ListItem' {
  declare module.exports: any;
}

declare module 'material-ui/List/ListItemAvatar' {
  declare module.exports: any;
}

declare module 'material-ui/List/ListItemIcon' {
  declare module.exports: any;
}

declare module 'material-ui/List/ListItemSecondaryAction' {
  declare module.exports: any;
}

declare module 'material-ui/List/ListItemText' {
  declare module.exports: any;
}

declare module 'material-ui/List/ListSubheader' {
  declare module.exports: any;
}

// Filename aliases
declare module 'material-ui/List/index' {
  declare module.exports: $Exports<'material-ui/List'>;
}
declare module 'material-ui/List/index.js' {
  declare module.exports: $Exports<'material-ui/List'>;
}
declare module 'material-ui/List/List.js' {
  declare module.exports: $Exports<'material-ui/List/List'>;
}
declare module 'material-ui/List/ListItem.js' {
  declare module.exports: $Exports<'material-ui/List/ListItem'>;
}
declare module 'material-ui/List/ListItemAvatar.js' {
  declare module.exports: $Exports<'material-ui/List/ListItemAvatar'>;
}
declare module 'material-ui/List/ListItemIcon.js' {
  declare module.exports: $Exports<'material-ui/List/ListItemIcon'>;
}
declare module 'material-ui/List/ListItemSecondaryAction.js' {
  declare module.exports: $Exports<'material-ui/List/ListItemSecondaryAction'>;
}
declare module 'material-ui/List/ListItemText.js' {
  declare module.exports: $Exports<'material-ui/List/ListItemText'>;
}
declare module 'material-ui/List/ListSubheader.js' {
  declare module.exports: $Exports<'material-ui/List/ListSubheader'>;
}
