// flow-typed signature: 6893fe909daf7234bf6d7b3d7a737d54
// flow-typed version: <<STUB>>/material-ui/styles_v1.0.0-beta.40/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'material-ui/styles'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'material-ui/styles' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'material-ui/styles/colorManipulator' {
  declare module.exports: any;
}

declare module 'material-ui/styles/createBreakpoints' {
  declare module.exports: any;
}

declare module 'material-ui/styles/createGenerateClassName' {
  declare module.exports: any;
}

declare module 'material-ui/styles/createMixins' {
  declare module.exports: any;
}

declare module 'material-ui/styles/createMuiTheme' {
  declare module.exports: any;
}

declare module 'material-ui/styles/createPalette' {
  declare module.exports: any;
}

declare module 'material-ui/styles/createTypography' {
  declare module.exports: any;
}

declare module 'material-ui/styles/getStylesCreator' {
  declare module.exports: any;
}

declare module 'material-ui/styles/getThemeProps' {
  declare module.exports: any;
}

declare module 'material-ui/styles/jssPreset' {
  declare module.exports: any;
}

declare module 'material-ui/styles/MuiThemeProvider' {
  declare module.exports: any;
}

declare module 'material-ui/styles/shadows' {
  declare module.exports: any;
}

declare module 'material-ui/styles/spacing' {
  declare module.exports: any;
}

declare module 'material-ui/styles/themeListener' {
  declare module.exports: any;
}

declare module 'material-ui/styles/transitions' {
  declare module.exports: any;
}

declare module 'material-ui/styles/withStyles' {
  declare module.exports: any;
}

declare module 'material-ui/styles/withTheme' {
  declare module.exports: any;
}

declare module 'material-ui/styles/zIndex' {
  declare module.exports: any;
}

// Filename aliases
declare module 'material-ui/styles/colorManipulator.js' {
  declare module.exports: $Exports<'material-ui/styles/colorManipulator'>;
}
declare module 'material-ui/styles/createBreakpoints.js' {
  declare module.exports: $Exports<'material-ui/styles/createBreakpoints'>;
}
declare module 'material-ui/styles/createGenerateClassName.js' {
  declare module.exports: $Exports<'material-ui/styles/createGenerateClassName'>;
}
declare module 'material-ui/styles/createMixins.js' {
  declare module.exports: $Exports<'material-ui/styles/createMixins'>;
}
declare module 'material-ui/styles/createMuiTheme.js' {
  declare module.exports: $Exports<'material-ui/styles/createMuiTheme'>;
}
declare module 'material-ui/styles/createPalette.js' {
  declare module.exports: $Exports<'material-ui/styles/createPalette'>;
}
declare module 'material-ui/styles/createTypography.js' {
  declare module.exports: $Exports<'material-ui/styles/createTypography'>;
}
declare module 'material-ui/styles/getStylesCreator.js' {
  declare module.exports: $Exports<'material-ui/styles/getStylesCreator'>;
}
declare module 'material-ui/styles/getThemeProps.js' {
  declare module.exports: $Exports<'material-ui/styles/getThemeProps'>;
}
declare module 'material-ui/styles/index' {
  declare module.exports: $Exports<'material-ui/styles'>;
}
declare module 'material-ui/styles/index.js' {
  declare module.exports: $Exports<'material-ui/styles'>;
}
declare module 'material-ui/styles/jssPreset.js' {
  declare module.exports: $Exports<'material-ui/styles/jssPreset'>;
}
declare module 'material-ui/styles/MuiThemeProvider.js' {
  declare module.exports: $Exports<'material-ui/styles/MuiThemeProvider'>;
}
declare module 'material-ui/styles/shadows.js' {
  declare module.exports: $Exports<'material-ui/styles/shadows'>;
}
declare module 'material-ui/styles/spacing.js' {
  declare module.exports: $Exports<'material-ui/styles/spacing'>;
}
declare module 'material-ui/styles/themeListener.js' {
  declare module.exports: $Exports<'material-ui/styles/themeListener'>;
}
declare module 'material-ui/styles/transitions.js' {
  declare module.exports: $Exports<'material-ui/styles/transitions'>;
}
declare module 'material-ui/styles/withStyles.js' {
  declare module.exports: $Exports<'material-ui/styles/withStyles'>;
}
declare module 'material-ui/styles/withTheme.js' {
  declare module.exports: $Exports<'material-ui/styles/withTheme'>;
}
declare module 'material-ui/styles/zIndex.js' {
  declare module.exports: $Exports<'material-ui/styles/zIndex'>;
}
